### ISSUE TITLE
Fix broken getBackend.test.js tests

### ISSUE THREAD

**Issue by taoeffect** [okTurtles/chel#22]
### Problem

```
$ deno task test   
Task test deno test --import-map=./vendor/import_map.json --allow-read=. --allow-write=test --no-remote
Check file:///@chelonia/chel/test/getBackend.test.ts
Check file:///@chelonia/chel/test/hash.test.ts
running 1 test from ./test/getBackend.test.ts
Tests for getBackend() ...
  it should fail given a non-existing folder if option `create` was not `true` ... ok (2ms)
  FS - should fail given a file instead of a folder ... FAILED (1ms)
  SQLite - should fail given a folder instead of a file ... FAILED (1ms)
  FS - it should open an existing folder as `fs` by default ... FAILED (0ms)
  FS - it should create the folder if missing and option `create` is `true` ... ok (0ms)
  SQLite - it should open an existing .db file as `sqlite` by default ... ok (11ms)
  SQLite - it should create the .db file if missing and option `create` is `true` ... ok (44ms)
Tests for getBackend() ... FAILED (due to 3 failed steps) (60ms)
running 1 test from ./test/hash.test.ts
Hash command tests ...
  it should create a raw CID for a plain text file ... ok (1ms)
  it should create a json CID for a json file ... ok (0ms)
Hash command tests ... ok (3ms)

 ERRORS 

Tests for getBackend() ... FS - should fail given a file instead of a folder => ./test/getBackend.test.ts:28:17
error: Leaking async ops:
  - 1 async operation to op_fs_mkdir_async was started in this test, but never completed.
To get more details where ops were leaked, run again with --trace-ops flag.

Tests for getBackend() ... SQLite - should fail given a folder instead of a file => ./test/getBackend.test.ts:36:17
error: AssertionError
    throw new AssertionError(msg);
          ^
    at assert (file:///@chelonia/chel/vendor/deno.land/std@0.141.0/testing/asserts.ts:132:11)
    at file:///@chelonia/chel/test/getBackend.test.ts:38:13
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async innerWrapped (ext:cli/40_testing.js:549:5)
    at async asyncOpSanitizer (ext:cli/40_testing.js:195:27)
    at async exitSanitizer (ext:cli/40_testing.js:478:27)
    at async Object.outerWrapped [as fn] (ext:cli/40_testing.js:492:14)
    at async TestContext.step (ext:cli/40_testing.js:1359:22)
    at async fn (file:///@chelonia/chel/test/getBackend.test.ts:36:9)

Tests for getBackend() ... FS - it should open an existing folder as `fs` by default => ./test/getBackend.test.ts:46:17
error: AssertionError
    throw new AssertionError(msg);
          ^
    at assert (file:///@chelonia/chel/vendor/deno.land/std@0.141.0/testing/asserts.ts:132:11)
    at file:///@chelonia/chel/test/getBackend.test.ts:48:13
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async innerWrapped (ext:cli/40_testing.js:549:5)
    at async asyncOpSanitizer (ext:cli/40_testing.js:195:27)
    at async exitSanitizer (ext:cli/40_testing.js:478:27)
    at async Object.outerWrapped [as fn] (ext:cli/40_testing.js:492:14)
    at async TestContext.step (ext:cli/40_testing.js:1359:22)
    at async fn (file:///@chelonia/chel/test/getBackend.test.ts:46:9)

 FAILURES 

Tests for getBackend() ... FS - should fail given a file instead of a folder => ./test/getBackend.test.ts:28:17
Tests for getBackend() ... SQLite - should fail given a folder instead of a file => ./test/getBackend.test.ts:36:17
Tests for getBackend() ... FS - it should open an existing folder as `fs` by default => ./test/getBackend.test.ts:46:17

FAILED | 1 passed (6 steps) | 1 failed (3 steps) (103ms)

error: Test failed
```

### Solution

Fix.

**Comment by snowteamer** [comment]
Awaiting every `assertRejects()` call seems to fix the issue.

**Comment by taoeffect** [comment]
@snowteamer Hmm, I still get this error:

```
% deno task test
Task test deno test --import-map=./vendor/import_map.json --allow-read=. --allow-write=test --no-remote
running 1 test from ./test/getBackend.test.ts
Tests for getBackend() ...
  it should fail given a non-existing folder if option `create` was not `true` ... ok (1ms)
  FS - should fail given a file instead of a folder ... ok (1ms)
  SQLite - should fail given a folder instead of a file ... FAILED (1ms)
  FS - it should open an existing folder as `fs` by default ... FAILED (1ms)
  FS - it should create the folder if missing and option `create` is `true` ... ok (0ms)
  SQLite - it should open an existing .db file as `sqlite` by default ... ok (11ms)
  SQLite - it should create the .db file if missing and option `create` is `true` ... ok (58ms)
Tests for getBackend() ... FAILED (due to 2 failed steps) (73ms)
running 1 test from ./test/hash.test.ts
Hash command tests ...
  it should create a raw CID for a plain text file ... ok (2ms)
  it should create a raw CID for a json file ... ok (0ms)
Hash command tests ... ok (2ms)

 ERRORS 

Tests for getBackend() ... SQLite - should fail given a folder instead of a file => ./test/getBackend.test.ts:36:17
error: AssertionError
    throw new AssertionError(msg);
          ^
    at assert (file:///@chelonia/chel/vendor/deno.land/std@0.141.0/testing/asserts.ts:132:11)
    at file:///@chelonia/chel/test/getBackend.test.ts:38:13
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async innerWrapped (ext:cli/40_testing.js:549:5)
    at async asyncOpSanitizer (ext:cli/40_testing.js:195:27)
    at async exitSanitizer (ext:cli/40_testing.js:478:27)
    at async Object.outerWrapped [as fn] (ext:cli/40_testing.js:492:14)
    at async TestContext.step (ext:cli/40_testing.js:1359:22)
    at async fn (file:///@chelonia/chel/test/getBackend.test.ts:36:9)

Tests for getBackend() ... FS - it should open an existing folder as `fs` by default => ./test/getBackend.test.ts:46:17
error: AssertionError
    throw new AssertionError(msg);
          ^
    at assert (file:///@chelonia/chel/vendor/deno.land/std@0.141.0/testing/asserts.ts:132:11)
    at file:///@chelonia/chel/test/getBackend.test.ts:48:13
    at eventLoopTick (ext:core/01_core.js:182:7)
    at async innerWrapped (ext:cli/40_testing.js:549:5)
    at async asyncOpSanitizer (ext:cli/40_testing.js:195:27)
    at async exitSanitizer (ext:cli/40_testing.js:478:27)
    at async Object.outerWrapped [as fn] (ext:cli/40_testing.js:492:14)
    at async TestContext.step (ext:cli/40_testing.js:1359:22)
    at async fn (file:///@chelonia/chel/test/getBackend.test.ts:46:9)

 FAILURES 

Tests for getBackend() ... SQLite - should fail given a folder instead of a file => ./test/getBackend.test.ts:36:17
Tests for getBackend() ... FS - it should open an existing folder as `fs` by default => ./test/getBackend.test.ts:46:17

FAILED | 1 passed (7 steps) | 1 failed (2 steps) (116ms)

error: Test failed
```
